version: "3"
services:
  redis.internal-bookingapp.com:
    container_name: backend
    image: redis:alpine
  home.internal-booking.com:
    container_name: frontend
    image: bookingappp-home:latest
    build:
      context: ./Bookingapp-home
    ports:
      - "8080:5000"
  movie.internal-bookingapp.com:
    container_name: movie
    image: bookingappp-movie:latest
    build:
      context: ./Bookingapp-movie
    ports:
      - "80:500"
  moviev2.internal-bookingapp.com:
    container_name: moviev2
    image: bookingappp-moviev2:latest
    build:
      context: ./Bookingapp-moviev2
    ports:
      - "81:5000"
